## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Gorom-Gorom,BF,87.64,broken clouds,14.4439,-0.2361,NaN
1,5,Worthington,US,86.05,light rain,40.0931,-83.0180,Sheraton Suites Columbus Worthington
2,7,Kapaa,US,75.52,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
3,9,Sechelt,CA,77.45,overcast clouds,49.4664,-123.7694,The Driftwood Inn
4,10,Garowe,SO,86.45,broken clouds,8.4054,48.4845,Curubo Hotel

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Trip into MEXICO.
# Grab the first hotel from the results and store the name.
mexico_vacation_df = vacation_df.loc[(vacation_df["Country"] == "MX")]
mexico_vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
32,102,Cabo San Lucas,MX,88.81,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
41,130,Zacualpan,MX,84.70,broken clouds,21.2500,-105.1667,La Colorada B&B
82,251,Ixtapa,MX,84.22,broken clouds,20.7000,-105.2000,Hotel Plaza Providencia
165,496,Pochutla,MX,89.82,overcast clouds,15.7432,-96.4661,Hotel Posada San Jose
196,581,Guerrero,MX,79.07,scattered clouds,17.6667,-100.0000,Villaxochilt
205,599,Coahuayana,MX,87.91,overcast clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
214,619,Asuncion Ixtaltepec,MX,86.92,overcast clouds,16.5000,-95.0500,Hotel San Rafael

In [6]:
new_column_order = ["City_ID", "City", "Country", "Lat","Lng", "Max Temp", "Current Description"]

In [7]:
mexico_vacation_df = mexico_vacation_df[new_column_order]

In [8]:
mexico_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
32,102,Cabo San Lucas,MX,22.8909,-109.9124,88.81,scattered clouds
41,130,Zacualpan,MX,21.2500,-105.1667,84.70,broken clouds
82,251,Ixtapa,MX,20.7000,-105.2000,84.22,broken clouds
165,496,Pochutla,MX,15.7432,-96.4661,89.82,overcast clouds
196,581,Guerrero,MX,17.6667,-100.0000,79.07,scattered clouds
205,599,Coahuayana,MX,18.7333,-103.6833,87.91,overcast clouds
214,619,Asuncion Ixtaltepec,MX,16.5000,-95.0500,86.92,overcast clouds
218,634,Sinaloa,MX,25.0000,-107.5000,88.11,scattered clouds

In [9]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# Let's pick by Minimum Temp to Maximum Temp cities. 
start = float(input("What is your Starting City_ID from MX List you would like for your trip? "))
stop1 = float(input("What is your First Stop City_ID from MX List you would like for your trip? "))
stop2 = float(input("What is your Second Stop City_ID from MX List you would like for your trip? "))
stop3 = float(input("What is your Thirth Stop City_ID from MX List you would like for your trip? "))
end = float(input("What is your Last City_ID from MX List you would like for your trip? "))

What is your Starting City_ID from MX List you would like for your trip? 102
What is your First Stop City_ID from MX List you would like for your trip? 130
What is your Second Stop City_ID from MX List you would like for your trip? 251
What is your Thirth Stop City_ID from MX List you would like for your trip? 496
What is your Last City_ID from MX List you would like for your trip? 581

In [10]:
 # 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop1)]
vacation_start = vacation_start.iloc[0]

vacation_stop1 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop2)]
vacation_stop1 = vacation_stop1.iloc[0]

vacation_stop2 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop3)]
vacation_stop2 = vacation_stop2.iloc[0]

vacation_stop3 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == end)]
vacation_stop3 = vacation_stop3.iloc[0]

vacation_end = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] <= end)]
vacation_end = vacation_end.iloc[0] 
                                     
print("Your Starting Destination is " + vacation_start["City"] + ", " + vacation_start["Country"])
print("Your Frist Stop is " + vacation_stop1["City"] + ", " + vacation_stop1["Country"])
print("Your Second Stop is " + vacation_stop2["City"] + ", " + vacation_stop2["Country"])                                     
print("Your Thirth Stop is " + vacation_stop3["City"] + ", " + vacation_stop3["Country"])                                     
print("Your Last Stop in your vacation is " + vacation_end["City"] + ", " + vacation_end["Country"])

Your Starting Destination is Zacualpan, MX
Your Frist Stop is Ixtapa, MX
Your Second Stop is Pochutla, MX
Your Thirth Stop is Guerrero, MX
Your Last Stop in your vacation is Cabo San Lucas, MX

In [11]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]]
end = vacation_end[["Lat", "Lng"]]
stop1 = vacation_stop1[["Lat", "Lng"]]
stop2 = vacation_stop2[["Lat", "Lng"]]
stop3 = vacation_stop3[["Lat", "Lng"]]
print(start, end, stop1, stop2, stop3)

Lat       21.25
Lng   -105.1667
Name: 41, dtype: object Lat     22.8909
Lng   -109.9124
Name: 32, dtype: object Lat     20.7
Lng   -105.2
Name: 82, dtype: object Lat    15.7432
Lng   -96.4661
Name: 165, dtype: object Lat    17.6667
Lng     -100.0
Name: 196, dtype: object

In [12]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start = (20.7, -105.2)
stop1 = (17.48, -91.43)
stop2 = (27.98, -114.06)
stop3 = (23.17, -97.95)
end = (30.85, -116.07)

fig = gmaps.figure()
sart2end_via_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(sart2end_via_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
mexico_vacation_df = pd.concat([mexico_vacation_df],ignore_index=True)
mexico_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
0,102,Cabo San Lucas,MX,22.8909,-109.9124,88.81,scattered clouds
1,130,Zacualpan,MX,21.2500,-105.1667,84.70,broken clouds
2,251,Ixtapa,MX,20.7000,-105.2000,84.22,broken clouds
3,496,Pochutla,MX,15.7432,-96.4661,89.82,overcast clouds
4,581,Guerrero,MX,17.6667,-100.0000,79.07,scattered clouds
5,599,Coahuayana,MX,18.7333,-103.6833,87.91,overcast clouds
6,619,Asuncion Ixtaltepec,MX,16.5000,-95.0500,86.92,overcast clouds
7,634,Sinaloa,MX,25.0000,-107.5000,88.11,scattered clouds

In [14]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
mark_info = [info_box_template.format(**row) for index, row in mexico_vacation_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = mexico_vacation_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map.
city_mark = mexico_vacation_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=mark_info)

fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))